// Site wall clock that walkins/crowds.trigger_date is stored in. NOW() is a
// timestamptz, so `AT TIME ZONE` yields the naive local time at that offset --
// the Postgres equivalent of the old CONVERT_TZ(NOW(), '+05:30', '+08:00'),
// minus the dependency on the server's configured time zone.
const SITE_WALL_TZ = "+08:00";

async function runMigrations(pool) {
  try {
    await ensureUpdatedAtFunction(pool);
    await ensureTriggers(pool);
    await ensureCameraAlertTable(pool);
  } catch (e) {
    console.error("[Migrations] Failed:", e.message || e);
  }
}

// Postgres has no `ON UPDATE CURRENT_TIMESTAMP`; a shared trigger stands in.
async function ensureUpdatedAtFunction(pool) {
  await pool.query(`
    CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $fn$
    BEGIN
      NEW.updated_at = LOCALTIMESTAMP;
      RETURN NEW;
    END;
    $fn$ LANGUAGE plpgsql
  `);
}

async function ensureTriggers(pool) {
  await pool.query(`
    CREATE OR REPLACE FUNCTION set_trigger_date() RETURNS trigger AS $fn$
    BEGIN
      NEW.trigger_date = NOW() AT TIME ZONE INTERVAL '${SITE_WALL_TZ}';
      RETURN NEW;
    END;
    $fn$ LANGUAGE plpgsql
  `);

  // pg_trigger rather than information_schema.triggers: the latter emits one
  // row per triggering event, and tgisinternal filters out FK-backing triggers.
  const [rows] = await pool.query(
    `SELECT t.tgname
       FROM pg_trigger t
       JOIN pg_class c ON c.oid = t.tgrelid
       JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = current_schema()
        AND NOT t.tgisinternal
        AND t.tgname IN ('walkins_set_trigger_date', 'crowds_set_trigger_date')`
  );
  const existing = new Set((rows || []).map((r) => r.tgname));

  for (const table of ["walkins", "crowds"]) {
    const name = `${table}_set_trigger_date`;
    if (existing.has(name)) continue;
    await pool.query(
      `CREATE TRIGGER ${name}
       BEFORE INSERT ON ${table} FOR EACH ROW
       EXECUTE FUNCTION set_trigger_date()`
    );
    console.log(`[Migrations] Created trigger: ${name}`);
  }
}

async function ensureCameraAlertTable(pool) {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS camera_alert_status (
      id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      camera_id        VARCHAR(100) NOT NULL,
      camera_name      VARCHAR(255) NOT NULL,
      status           VARCHAR(16)  NOT NULL DEFAULT 'offline',
      last_seen_online TIMESTAMP    NULL,
      offline_since    TIMESTAMP    NULL,
      alert_sent_at    TIMESTAMP    NULL,
      updated_at       TIMESTAMP    NOT NULL DEFAULT LOCALTIMESTAMP,
      CONSTRAINT uq_camera_id UNIQUE (camera_id),
      CONSTRAINT ck_camera_alert_status CHECK (status IN ('online','offline'))
    )
  `);

  await pool.query(`DROP TRIGGER IF EXISTS camera_alert_status_set_updated_at ON camera_alert_status`);
  await pool.query(`
    CREATE TRIGGER camera_alert_status_set_updated_at
      BEFORE UPDATE ON camera_alert_status
      FOR EACH ROW EXECUTE FUNCTION set_updated_at()
  `);
}

module.exports = { runMigrations };
