-- Persistent audit log for /assistant and /assistant_enhance interactions.
-- Apply: psql -U aiserver -d aiserver -f server/sql/assistant_chat_audit.sql

CREATE TABLE IF NOT EXISTS assistant_chat_audit (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id           VARCHAR(64)  NOT NULL,
  user_id              BIGINT       NOT NULL,
  username             VARCHAR(255) NULL,
  email                VARCHAR(255) NOT NULL,
  role                 VARCHAR(64)  NOT NULL,
  -- MySQL ENUM has no Postgres equivalent that is as easy to extend; a CHECK
  -- gives the same guarantee and still reads back as a plain string.
  route                VARCHAR(32)  NOT NULL,
  question             TEXT         NOT NULL,
  answer               TEXT         NULL,
  objective            VARCHAR(128) NULL,
  metric               VARCHAR(128) NULL,
  generated_sql        TEXT         NULL,
  planner_context_json JSONB        NULL,
  entities_json        JSONB        NULL,
  analytics_json       JSONB        NULL,
  latency_ms           INTEGER      NULL,
  created_at           TIMESTAMP    NOT NULL DEFAULT LOCALTIMESTAMP,
  CONSTRAINT ck_assistant_audit_route CHECK (route IN ('assistant','assistant_enhance'))
);

CREATE INDEX IF NOT EXISTS idx_assistant_audit_user_id      ON assistant_chat_audit (user_id);
CREATE INDEX IF NOT EXISTS idx_assistant_audit_session_id   ON assistant_chat_audit (session_id);
CREATE INDEX IF NOT EXISTS idx_assistant_audit_route        ON assistant_chat_audit (route);
CREATE INDEX IF NOT EXISTS idx_assistant_audit_created_at   ON assistant_chat_audit (created_at);
CREATE INDEX IF NOT EXISTS idx_assistant_audit_user_created ON assistant_chat_audit (user_id, created_at);
