-- ---------------------------------------------------------------------------
-- Local development bootstrap for the ANPR stack (PostgreSQL).
--
-- Creates every table the Express API reads from and fills it with synthetic
-- demo data so the dashboard, reports, violations and watchlist screens have
-- something to render without a live receiver pipeline.
--
-- Apply:  psql -U aiserver -d aiserver -f server/sql/dev_bootstrap.sql
--
-- IMPORTANT: run this BEFORE starting the API. src/lib/dbMigrations.js installs
-- BEFORE INSERT triggers on walkins and crowds that overwrite trigger_date,
-- which would flatten the seeded history into "now". To re-seed later, drop
-- walkins_set_trigger_date / crowds_set_trigger_date first.
--
-- Time semantics (see src/eventTimeSql.js + config/site.config.json):
--   vehicle_events.created_at   -> stored as DB wall clock (+05:30), shown +08:00
--   walkins/crowds.trigger_date -> already stored in site time (+08:00)
-- Every datetime column is TIMESTAMP (no time zone), i.e. a naive wall clock,
-- and the offsets are applied explicitly with AT TIME ZONE. Unlike the MySQL
-- build, nothing depends on the server's configured time zone.
-- ---------------------------------------------------------------------------

-- --------------------------------------------------------------------------
-- Shared helpers
-- --------------------------------------------------------------------------

-- Postgres has no `ON UPDATE CURRENT_TIMESTAMP`; a trigger stands in for it.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = LOCALTIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- --------------------------------------------------------------------------
-- Schema
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS sites (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

-- Native app users (primary login source).
CREATE TABLE IF NOT EXISTS anpr_app_users (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email                VARCHAR(255) NOT NULL,
  password_hash        VARCHAR(255) NOT NULL,
  role                 VARCHAR(64)  NOT NULL DEFAULT 'viewer',
  must_change_password SMALLINT     NOT NULL DEFAULT 0,
  token_version        INTEGER      NOT NULL DEFAULT 0,
  locked_until         TIMESTAMP    NULL,
  disabled_at          TIMESTAMP    NULL,
  created_at           TIMESTAMP    NOT NULL DEFAULT LOCALTIMESTAMP,
  CONSTRAINT uq_anpr_users_email UNIQUE (email)
);

-- Legacy Laravel user table; routes/auth.js falls back to it on a miss.
CREATE TABLE IF NOT EXISTS users (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email     VARCHAR(255) NOT NULL,
  password  VARCHAR(255) NULL,
  role_name VARCHAR(64)  NULL,
  status    VARCHAR(32)  NOT NULL DEFAULT 'active',
  CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS vehicle_events (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id              VARCHAR(64)  NOT NULL,
  camera_id             VARCHAR(100) NOT NULL,
  vehicle_num           VARCHAR(32)  NULL,
  vehicle_num_raw       VARCHAR(32)  NULL,
  vehicle_category      INTEGER      NULL,
  vehicle_type          VARCHAR(32)  NULL,
  ocr_confidence        NUMERIC(6,2) NULL,
  plate_read_trust      VARCHAR(16)  NULL,
  plate_read_risk_flags JSONB        NULL,
  plate_read_metrics    JSONB        NULL,
  "timestamp"           BIGINT       NOT NULL DEFAULT 0,
  full_image_url        VARCHAR(512) NULL,
  plate_url             VARCHAR(512) NULL,
  -- Set when an operator hand-corrects the plate via /api/challan/confirm-plate.
  was_corrected         SMALLINT     NOT NULL DEFAULT 0,
  created_at            TIMESTAMP    NOT NULL DEFAULT LOCALTIMESTAMP,
  CONSTRAINT uq_ve_event_id UNIQUE (event_id)
);
CREATE INDEX IF NOT EXISTS idx_ve_created_at ON vehicle_events (created_at);
CREATE INDEX IF NOT EXISTS idx_ve_camera     ON vehicle_events (camera_id);
CREATE INDEX IF NOT EXISTS idx_ve_plate      ON vehicle_events (vehicle_num);

CREATE TABLE IF NOT EXISTS traffic_violations (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id       VARCHAR(64)  NOT NULL,
  violation_type VARCHAR(64)  NOT NULL,
  score          NUMERIC(6,3) NULL,
  feedback       SMALLINT     DEFAULT NULL,
  feedback_at    TIMESTAMP    DEFAULT NULL,
  feedback_by    VARCHAR(191) DEFAULT NULL,
  created_at     TIMESTAMP    NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_tv_event_id ON traffic_violations (event_id);
CREATE INDEX IF NOT EXISTS idx_tv_type     ON traffic_violations (violation_type);
CREATE INDEX IF NOT EXISTS idx_tv_feedback ON traffic_violations (feedback);
COMMENT ON COLUMN traffic_violations.feedback IS 'NULL=unrated,1=confirmed,0=false_positive';

-- One row per violation that has been actioned (challan issued or dismissed).
CREATE TABLE IF NOT EXISTS violation_ticket_flags (
  violation_id BIGINT      NOT NULL PRIMARY KEY,
  flag         SMALLINT    NOT NULL DEFAULT 0,
  challan_id   VARCHAR(64) NULL,
  created_at   TIMESTAMP   NOT NULL DEFAULT LOCALTIMESTAMP,
  updated_at   TIMESTAMP   NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_vtf_updated ON violation_ticket_flags (updated_at);
COMMENT ON COLUMN violation_ticket_flags.flag IS '1=challan generated, 0=invalid';

DROP TRIGGER IF EXISTS violation_ticket_flags_set_updated_at ON violation_ticket_flags;
CREATE TRIGGER violation_ticket_flags_set_updated_at
  BEFORE UPDATE ON violation_ticket_flags
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS walkins (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id      INTEGER      NOT NULL DEFAULT 1,
  camera_id    VARCHAR(100) NOT NULL,
  gender       VARCHAR(16)  NOT NULL DEFAULT 'unknown',
  image_path   VARCHAR(512) NULL,
  trigger_date TIMESTAMP    NULL,
  CONSTRAINT ck_walkins_gender CHECK (gender IN ('male','female','unknown'))
);
CREATE INDEX IF NOT EXISTS idx_walkins_trigger ON walkins (trigger_date);
CREATE INDEX IF NOT EXISTS idx_walkins_camera  ON walkins (camera_id);
CREATE INDEX IF NOT EXISTS idx_walkins_gender  ON walkins (gender);

CREATE TABLE IF NOT EXISTS crowds (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id       INTEGER      NOT NULL DEFAULT 1,
  site_name     VARCHAR(255) NULL,
  camera_id     VARCHAR(100) NOT NULL,
  alert_type    VARCHAR(32)  NOT NULL DEFAULT 'intrusion',
  people_count  INTEGER      NOT NULL DEFAULT 0,
  occupancy_pct NUMERIC(6,2) NOT NULL DEFAULT 0,
  image_path    VARCHAR(512) NULL,
  trigger_date  TIMESTAMP    NULL,
  CONSTRAINT ck_crowds_alert_type CHECK (alert_type IN
    ('intrusion','unauthorized_access','camera_tampering','unattended_kitchen','understaffed_kitchen'))
);
CREATE INDEX IF NOT EXISTS idx_crowds_trigger    ON crowds (trigger_date);
CREATE INDEX IF NOT EXISTS idx_crowds_camera     ON crowds (camera_id);
CREATE INDEX IF NOT EXISTS idx_crowds_alert_type ON crowds (alert_type);

-- Watchlist model. lpr_vehicle_lists stores unix seconds in created_at/updated_at
-- (routes/watchlist.js writes Math.floor(Date.now()/1000)); lpr_rules uses NOW().
CREATE TABLE IF NOT EXISTS lpr_vehicle_lists (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enabled    SMALLINT     NOT NULL DEFAULT 1,
  name       VARCHAR(255) NOT NULL,
  notes      TEXT         NULL,
  site_id    INTEGER      NOT NULL DEFAULT 1,
  created_at BIGINT       NULL,
  updated_at BIGINT       NULL
);

CREATE TABLE IF NOT EXISTS lpr_vehicle_list_vehicles (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_list_id INTEGER   NOT NULL,
  conditions      TEXT      NULL,
  created_at      TIMESTAMP NULL,
  updated_at      TIMESTAMP NULL
);
CREATE INDEX IF NOT EXISTS idx_lvlv_list ON lpr_vehicle_list_vehicles (vehicle_list_id);

-- barrierOpen / filterType / vehicleListIds are read back by name in
-- src/lib/watchlistDb.js, so they stay camelCase and must always be quoted.
CREATE TABLE IF NOT EXISTS lpr_rules (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enabled          SMALLINT     NOT NULL DEFAULT 1,
  "barrierOpen"    SMALLINT     NOT NULL DEFAULT 0,
  "filterType"     VARCHAR(32)  NOT NULL DEFAULT 'plate',
  "vehicleListIds" TEXT         NULL,
  name             VARCHAR(255) NOT NULL,
  access_type      VARCHAR(64)  NULL,
  security_type    VARCHAR(64)  NULL,
  priority         INTEGER      NOT NULL DEFAULT 10,
  site_id          INTEGER      NOT NULL DEFAULT 1,
  conditions       TEXT         NULL,
  notes            TEXT         NULL,
  valid_from       TIMESTAMP    NULL,
  valid_to         TIMESTAMP    NULL,
  created_at       TIMESTAMP    NULL,
  updated_at       TIMESTAMP    NULL
);
CREATE INDEX IF NOT EXISTS idx_rules_site ON lpr_rules (site_id);

-- Optional legacy tables the watchlist "hits" endpoint probes for.
CREATE TABLE IF NOT EXISTS events (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id VARCHAR(64) NOT NULL,
  lp       VARCHAR(32) NULL
);
CREATE INDEX IF NOT EXISTS idx_events_event_id ON events (event_id);

CREATE TABLE IF NOT EXISTS rule_event_triggers (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_id      INTEGER     NULL,
  event_id     VARCHAR(64) NULL,
  trigger_date TIMESTAMP   NULL
);
CREATE INDEX IF NOT EXISTS idx_ret_trigger ON rule_event_triggers (trigger_date);

-- Also created at boot by src/lib/dbMigrations.js; declared here so a fresh
-- bootstrap is complete on its own.
CREATE TABLE IF NOT EXISTS camera_alert_status (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camera_id        VARCHAR(100) NOT NULL,
  camera_name      VARCHAR(255) NOT NULL,
  status           VARCHAR(16)  NOT NULL DEFAULT 'offline',
  last_seen_online TIMESTAMP    NULL,
  offline_since    TIMESTAMP    NULL,
  alert_sent_at    TIMESTAMP    NULL,
  updated_at       TIMESTAMP    NOT NULL DEFAULT LOCALTIMESTAMP,
  CONSTRAINT uq_camera_id UNIQUE (camera_id),
  CONSTRAINT ck_camera_alert_status CHECK (status IN ('online','offline'))
);

DROP TRIGGER IF EXISTS camera_alert_status_set_updated_at ON camera_alert_status;
CREATE TRIGGER camera_alert_status_set_updated_at
  BEFORE UPDATE ON camera_alert_status
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS assistant_chat_audit (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id           VARCHAR(64)  NOT NULL,
  user_id              BIGINT       NOT NULL,
  username             VARCHAR(255) NULL,
  email                VARCHAR(255) NOT NULL,
  role                 VARCHAR(64)  NOT NULL,
  route                VARCHAR(32)  NOT NULL,
  question             TEXT         NOT NULL,
  answer               TEXT         NULL,
  objective            VARCHAR(128) NULL,
  metric               VARCHAR(128) NULL,
  generated_sql        TEXT         NULL,
  planner_context_json JSONB        NULL,
  entities_json        JSONB        NULL,
  analytics_json       JSONB        NULL,
  latency_ms           INTEGER      NULL,
  created_at           TIMESTAMP    NOT NULL DEFAULT LOCALTIMESTAMP,
  CONSTRAINT ck_assistant_audit_route CHECK (route IN ('assistant','assistant_enhance'))
);
CREATE INDEX IF NOT EXISTS idx_assistant_audit_user_id      ON assistant_chat_audit (user_id);
CREATE INDEX IF NOT EXISTS idx_assistant_audit_session_id   ON assistant_chat_audit (session_id);
CREATE INDEX IF NOT EXISTS idx_assistant_audit_route        ON assistant_chat_audit (route);
CREATE INDEX IF NOT EXISTS idx_assistant_audit_created_at   ON assistant_chat_audit (created_at);
CREATE INDEX IF NOT EXISTS idx_assistant_audit_user_created ON assistant_chat_audit (user_id, created_at);

-- --------------------------------------------------------------------------
-- Reference data
-- --------------------------------------------------------------------------

INSERT INTO sites (id, name) VALUES
  (1, 'Biryani Katha'),
  (2, 'Biryani Katha - Banquet')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- Explicit ids do not advance an identity sequence; realign it so later
-- inserts that omit id do not collide.
SELECT setval(pg_get_serial_sequence('sites', 'id'), COALESCE((SELECT MAX(id) FROM sites), 1));

-- admin@anpr.local  / Admin@123
-- viewer@anpr.local / Viewer@123
INSERT INTO anpr_app_users (email, password_hash, role, must_change_password) VALUES
  ('admin@anpr.local',  '$2b$10$uj7Lffbyp5Hs3Z9rRsiv1ech8Y38lYCQ./inpYrJzFRWXgdY537hC', 'admin',  0),
  ('viewer@anpr.local', '$2b$10$D7PymnEEHz/QoPUnINTcuetWdyE0wQ0RNz.H2szDRE58eSWz7EK7W', 'viewer', 0)
ON CONFLICT (email) DO UPDATE
  SET password_hash = EXCLUDED.password_hash, role = EXCLUDED.role;

-- --------------------------------------------------------------------------
-- vehicle_events: ~4500 plate reads spread over the last 30 days
--
-- MySQL's _seed_seq helper table is replaced by generate_series(), and
-- ELT(FLOOR(RAND() * n) + 1, ...) by indexing into an ARRAY literal.
-- --------------------------------------------------------------------------

TRUNCATE TABLE vehicle_events RESTART IDENTITY;

INSERT INTO vehicle_events
  (event_id, camera_id, vehicle_num, vehicle_num_raw, vehicle_category, vehicle_type,
   ocr_confidence, plate_read_trust, plate_read_risk_flags, plate_read_metrics,
   "timestamp", full_image_url, plate_url, created_at)
SELECT
  'EV' || LPAD(t.n::text, 8, '0'),
  t.cam,
  -- Plate is a pure function of t.idx, so both columns get the same value.
  t.plate,
  t.plate,
  t.cat,
  t.vtype,
  t.conf,
  t.trust,
  CASE t.trust
    WHEN 'low'    THEN jsonb_build_array('low_ocr_conf')
    WHEN 'medium' THEN jsonb_build_array('medium_ocr_conf')
    ELSE jsonb_build_array()
  END,
  jsonb_build_object(
    'trust', t.trust,
    'ocr_confidence', t.conf,
    'quality_band', CASE t.trust WHEN 'high' THEN 'excellent' WHEN 'medium' THEN 'good' ELSE 'fair' END,
    'readable_crop', t.trust <> 'low',
    'factors', jsonb_build_array('Plate crop sharpness score: ' || ROUND(t.conf / 100, 2))
  ),
  0,
  'receiver-results/' || t.cam || '/scene/' || LPAD(t.n::text, 8, '0') || '.jpg',
  'receiver-results/' || t.cam || '/plate/' || LPAD(t.n::text, 8, '0') || '.jpg',
  -- Roll back a day if the randomised clock landed in the future.
  CASE WHEN t.ts > LOCALTIMESTAMP THEN t.ts - INTERVAL '1 day' ELSE t.ts END
FROM (
  SELECT
    b.*,
    CHR(65 + (b.idx * 7)  % 26) ||
    CHR(65 + (b.idx * 13) % 26) ||
    CHR(65 + (b.idx * 3)  % 26) ||
    ' ' || LPAD(((b.idx * 23) % 10000)::text, 4, '0') AS plate
  FROM (
    SELECT
      s.n,
      (ARRAY['AEYE_2','AEYE_4','AEYE_5','AEYE_6'])[(FLOOR(RANDOM() * 4) + 1)::int] AS cam,
      -- ~420 recurring plates so top-plates / journey screens have real repeats
      FLOOR(RANDOM() * 420)::int AS idx,
      FLOOR(RANDOM() * 12)::int + 1 AS cat,
      (ARRAY['PRIVATE','PRIVATE','PRIVATE','PRIVATE','PRIVATE',
             'PUBLIC_UTILITY','PUBLIC_UTILITY','PUBLIC_UTILITY','ELECTRIC','PRIVATE'
            ])[(FLOOR(RANDOM() * 10) + 1)::int] AS vtype,
      ROUND((55 + RANDOM() * 44)::numeric, 2) AS conf,
      (ARRAY['high','high','high','high','high','high','medium','medium','medium','low'
            ])[(FLOOR(RANDOM() * 10) + 1)::int] AS trust,
      (CURRENT_DATE - FLOOR(RANDOM() * 30)::int)
        -- Diurnal shape: busiest between 07:00 and 20:00
        + MAKE_TIME(LEAST(23, FLOOR(5 + 18 * POWER(RANDOM(), 0.85))::int),
                    FLOOR(RANDOM() * 60)::int,
                    FLOOR(RANDOM() * 60)::double precision) AS ts
    FROM generate_series(0, 4499) AS s(n)
  ) b
) t;

-- Mirror plates into the legacy `events` table used by watchlist hits.
TRUNCATE TABLE events RESTART IDENTITY;
INSERT INTO events (event_id, lp)
SELECT event_id, vehicle_num FROM vehicle_events;

-- --------------------------------------------------------------------------
-- traffic_violations: ~7% of reads, weighted toward two-wheeler offences
-- --------------------------------------------------------------------------

TRUNCATE TABLE traffic_violations RESTART IDENTITY;

INSERT INTO traffic_violations (event_id, violation_type, score, feedback, created_at)
SELECT
  ve.event_id,
  (ARRAY['NO_HELMET','NO_HELMET','NO_HELMET',
         'TRIPLE_RIDING','TRIPLE_RIDING',
         'WRONG_ROUTE','WRONG_ROUTE',
         'WRONG_PARKING'])[(FLOOR(RANDOM() * 8) + 1)::int],
  ROUND((0.55 + RANDOM() * 0.44)::numeric, 3),
  -- Mostly unrated; a few thumbs-up, a couple flagged as false positives
  (ARRAY[NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,1,0]::smallint[]
        )[(FLOOR(RANDOM() * 12) + 1)::int],
  ve.created_at
FROM vehicle_events ve
WHERE RANDOM() < 0.07;

-- Mark a slice of violations as already actioned so challan history and the
-- "pending review" counters are not empty.
TRUNCATE TABLE violation_ticket_flags;

INSERT INTO violation_ticket_flags (violation_id, flag, challan_id, created_at, updated_at)
SELECT
  tv.id,
  CASE WHEN RANDOM() < 0.8 THEN 1 ELSE 0 END,
  'CHL-' || TO_CHAR(CURRENT_DATE, 'YYYYMM') || '-' || LPAD(tv.id::text, 6, '0'),
  tv.created_at,
  tv.created_at
FROM traffic_violations tv
WHERE RANDOM() < 0.25;

-- --------------------------------------------------------------------------
-- walkins / crowds
--
-- trigger_date is stored in SITE time (+08:00), unlike vehicle_events.created_at.
-- MySQL used session variables for @site_now / @site_today; here the expression
-- is inlined, since NOW() AT TIME ZONE does not depend on the server setting.
-- --------------------------------------------------------------------------

TRUNCATE TABLE walkins RESTART IDENTITY;

INSERT INTO walkins (site_id, camera_id, gender, image_path, trigger_date)
SELECT
  1,
  'Right Entrance',
  t.gender,
  'walkins/' || TO_CHAR(t.ts, 'YYYY-MM-DD') || '/frame_' || LPAD(t.n::text, 6, '0') || '.jpg',
  CASE WHEN t.ts > (NOW() AT TIME ZONE INTERVAL '+08:00') THEN t.ts - INTERVAL '1 day' ELSE t.ts END
FROM (
  SELECT
    s.n,
    -- Roughly 55% male, 40% female, 5% not classified
    (ARRAY['male','male','male','male','male','male','male','male','male','male','male',
           'female','female','female','female','female','female','female',
           'unknown','unknown'])[(FLOOR(RANDOM() * 20) + 1)::int] AS gender,
    (((NOW() AT TIME ZONE INTERVAL '+08:00')::date) - FLOOR(RANDOM() * 30)::int)
      -- Office footfall: 08:00 - 17:00
      + MAKE_TIME(FLOOR(8 + RANDOM() * 9)::int,
                  FLOOR(RANDOM() * 60)::int,
                  FLOOR(RANDOM() * 60)::double precision) AS ts
  FROM generate_series(0, 899) AS s(n)
) t;

TRUNCATE TABLE crowds RESTART IDENTITY;

INSERT INTO crowds (site_id, site_name, camera_id, alert_type, people_count, occupancy_pct, image_path, trigger_date)
SELECT
  1,
  'Biryani Katha',
  'Overview',
  t.alert_type,
  t.people,
  -- severityAlarm 70 / severityCritical 85 per config/site.config.json
  LEAST(100, ROUND((t.people * 1.45)::numeric, 2)),
  'crowds/' || TO_CHAR(t.ts, 'YYYY-MM-DD') || '/frame_' || LPAD(t.n::text, 6, '0') || '.jpg',
  CASE WHEN t.ts > (NOW() AT TIME ZONE INTERVAL '+08:00') THEN t.ts - INTERVAL '1 day' ELSE t.ts END
FROM (
  SELECT
    s.n,
    FLOOR(28 + RANDOM() * 40)::int AS people,
    -- Roughly 35% intrusion, 15% unauthorized, 15% tampering, 15% unattended,
    -- 20% understaffed
    (ARRAY['intrusion','intrusion','intrusion','intrusion','intrusion','intrusion','intrusion',
           'unauthorized_access','unauthorized_access','unauthorized_access',
           'camera_tampering','camera_tampering','camera_tampering',
           'unattended_kitchen','unattended_kitchen','unattended_kitchen',
           'understaffed_kitchen','understaffed_kitchen','understaffed_kitchen','understaffed_kitchen'
          ])[(FLOOR(RANDOM() * 20) + 1)::int] AS alert_type,
    (((NOW() AT TIME ZONE INTERVAL '+08:00')::date) - FLOOR(RANDOM() * 30)::int)
      + MAKE_TIME(FLOOR(8 + RANDOM() * 10)::int,
                  FLOOR(RANDOM() * 60)::int,
                  FLOOR(RANDOM() * 60)::double precision) AS ts
  FROM generate_series(0, 619) AS s(n)
) t;

-- --------------------------------------------------------------------------
-- Watchlists: two lists plus matching rules, seeded from plates that actually
-- appear in the reads so the watchlist hit panel resolves against vehicle_events.
-- --------------------------------------------------------------------------

TRUNCATE TABLE lpr_vehicle_list_vehicles RESTART IDENTITY;
TRUNCATE TABLE lpr_vehicle_lists RESTART IDENTITY;
TRUNCATE TABLE lpr_rules RESTART IDENTITY;
TRUNCATE TABLE rule_event_triggers RESTART IDENTITY;

INSERT INTO lpr_vehicle_lists (id, enabled, name, notes, site_id, created_at, updated_at) VALUES
  (1, 1, 'Stolen Vehicles', 'Plates reported stolen to the station desk.',
   1, EXTRACT(EPOCH FROM NOW())::bigint, EXTRACT(EPOCH FROM NOW())::bigint),
  (2, 1, 'VIP Convoy',      'Cleared for barrier-free entry.',
   1, EXTRACT(EPOCH FROM NOW())::bigint, EXTRACT(EPOCH FROM NOW())::bigint);
SELECT setval(pg_get_serial_sequence('lpr_vehicle_lists', 'id'),
              COALESCE((SELECT MAX(id) FROM lpr_vehicle_lists), 1));

INSERT INTO lpr_vehicle_list_vehicles (vehicle_list_id, conditions, created_at, updated_at)
SELECT
  CASE WHEN x.rn <= 8 THEN 1 ELSE 2 END,
  jsonb_build_array(jsonb_build_object('lp', jsonb_build_object('eq', x.vehicle_num)))::text,
  LOCALTIMESTAMP,
  LOCALTIMESTAMP
FROM (
  SELECT vehicle_num, ROW_NUMBER() OVER (ORDER BY COUNT(*) DESC) AS rn
  FROM vehicle_events
  WHERE vehicle_num IS NOT NULL AND vehicle_num <> ''
  GROUP BY vehicle_num
  ORDER BY COUNT(*) DESC
  LIMIT 12
) x;

INSERT INTO lpr_rules
  (id, enabled, "barrierOpen", "filterType", "vehicleListIds", name, access_type, security_type,
   priority, site_id, conditions, notes, valid_from, valid_to, created_at, updated_at)
VALUES
  (1, 1, 0, 'vehicleList', '["Stolen Vehicles"]', 'Stolen vehicle alert', 'deny', 'alarm', 5, 1,
   jsonb_build_array(jsonb_build_object('_cameras',
     jsonb_build_object('ids', jsonb_build_array('AEYE_2','AEYE_4','AEYE_5','AEYE_6'))))::text,
   'Raise an alarm on any camera.', NULL, NULL, LOCALTIMESTAMP, LOCALTIMESTAMP),
  (2, 1, 1, 'vehicleList', '["VIP Convoy"]', 'VIP convoy pass', 'allow', 'notify', 20, 1,
   jsonb_build_array(jsonb_build_object('_cameras',
     jsonb_build_object('ids', jsonb_build_array('AEYE_6'))))::text,
   'Bridge camera only.', NULL, NULL, LOCALTIMESTAMP, LOCALTIMESTAMP);
SELECT setval(pg_get_serial_sequence('lpr_rules', 'id'),
              COALESCE((SELECT MAX(id) FROM lpr_rules), 1));

-- Historic trigger rows so /watchlist/hits has data from the triggers source.
INSERT INTO rule_event_triggers (rule_id, event_id, trigger_date)
SELECT
  1,
  ve.event_id,
  (ve.created_at AT TIME ZONE INTERVAL '+05:30') AT TIME ZONE INTERVAL '+08:00'
FROM vehicle_events ve
JOIN lpr_vehicle_list_vehicles v
  ON v.vehicle_list_id = 1
 AND (v.conditions::jsonb -> 0 -> 'lp' ->> 'eq') = ve.vehicle_num
ORDER BY ve.created_at DESC
LIMIT 120;

-- --------------------------------------------------------------------------

SELECT 'vehicle_events'     AS table_name, COUNT(*) AS rows_seeded FROM vehicle_events
UNION ALL SELECT 'traffic_violations',     COUNT(*) FROM traffic_violations
UNION ALL SELECT 'violation_ticket_flags', COUNT(*) FROM violation_ticket_flags
UNION ALL SELECT 'walkins',                COUNT(*) FROM walkins
UNION ALL SELECT 'crowds',                 COUNT(*) FROM crowds
UNION ALL SELECT 'rule_event_triggers',    COUNT(*) FROM rule_event_triggers
UNION ALL SELECT 'anpr_app_users',         COUNT(*) FROM anpr_app_users;
