-- ---------------------------------------------------------------------------
-- Inference viewer: S3 (bk-inference-storage) -> PostgreSQL
--
-- Read side for the four on-prem CV services. Every row points at exactly one
-- S3 object via media_asset; the frontend never sees an S3 URL, only a
-- short-TTL presigned link minted on demand.
--
-- Apply: psql -U aiserver -d aiserver -f server/sql/inference_viewer.sql
-- Safe to re-run.
--
-- Timezone contract:
--   Every *_at column is TIMESTAMPTZ (absolute instants), unlike the older
--   ANPR tables which store naive wall clocks. The ingester localises the
--   naive-IST intrusion timestamps and filename-derived times to Asia/Kolkata
--   before insert; walkins timestamps already carry +00:00.
-- ---------------------------------------------------------------------------

-- Camera ids are inconsistent across services by design
-- ('cam-after hours -1 ', 'Camera_Loitering-1', 'intr-1', 'cam-1'), so they are
-- looked up rather than normalised in code. camera_key is stored verbatim,
-- trailing spaces and all.
CREATE TABLE IF NOT EXISTS inference_camera (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service      VARCHAR(32)  NOT NULL,
  camera_key   VARCHAR(200) NOT NULL,
  display_name VARCHAR(200) NULL,
  first_seen   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT uq_inference_camera UNIQUE (service, camera_key)
);

-- One row per S3 object. s3_key is the natural key; re-ingesting an object
-- updates size/etag rather than duplicating.
CREATE TABLE IF NOT EXISTS media_asset (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  s3_key        TEXT         NOT NULL,
  service       VARCHAR(32)  NOT NULL,
  artefact_type VARCHAR(32)  NOT NULL,
  camera_key    VARCHAR(200) NULL,
  captured_at   TIMESTAMPTZ  NULL,
  folder_date   DATE         NULL,   -- the <YYYY-MM-DD> path segment (mtime/IST)
  size_bytes    BIGINT       NULL,
  content_type  VARCHAR(100) NULL,
  etag          VARCHAR(100) NULL,
  last_modified TIMESTAMPTZ  NULL,
  ingested_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT uq_media_asset_key UNIQUE (s3_key)
);
CREATE INDEX IF NOT EXISTS idx_media_asset_captured  ON media_asset (captured_at DESC);
CREATE INDEX IF NOT EXISTS idx_media_asset_service   ON media_asset (service, artefact_type);
CREATE INDEX IF NOT EXISTS idx_media_asset_camera    ON media_asset (camera_key);

-- --------------------------------------------------------------------------
-- after_hours: presence stills, 23:00-07:00. No sidecar; filename is the only
-- metadata. tag is GID<n> (re-identified) or S<n> (session).
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS after_hours_sighting (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camera_key  VARCHAR(200) NOT NULL,
  captured_at TIMESTAMPTZ  NOT NULL,
  tag         VARCHAR(32)  NULL,
  global_id   INTEGER      NULL,
  session_id  INTEGER      NULL,
  asset_id    BIGINT       NOT NULL REFERENCES media_asset(id) ON DELETE CASCADE,
  CONSTRAINT uq_after_hours_asset UNIQUE (asset_id)
);
CREATE INDEX IF NOT EXISTS idx_ahs_captured ON after_hours_sighting (captured_at DESC);
CREATE INDEX IF NOT EXISTS idx_ahs_camera   ON after_hours_sighting (camera_key);

-- --------------------------------------------------------------------------
-- loitering: dwell clips, 30-40 MB. No sidecar. The GID segment is optional.
-- started_at comes from the filename's own date/time, which can disagree with
-- the S3 folder date (folder = mtime).
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS loitering_event (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stream        VARCHAR(200) NOT NULL,
  global_id     INTEGER      NULL,
  session_id    INTEGER      NULL,
  dwell_seconds INTEGER      NULL,
  started_at    TIMESTAMPTZ  NOT NULL,
  asset_id      BIGINT       NOT NULL REFERENCES media_asset(id) ON DELETE CASCADE,
  CONSTRAINT uq_loitering_asset UNIQUE (asset_id)
);
CREATE INDEX IF NOT EXISTS idx_loiter_started ON loitering_event (started_at DESC);
CREATE INDEX IF NOT EXISTS idx_loiter_stream  ON loitering_event (stream);
CREATE INDEX IF NOT EXISTS idx_loiter_dwell   ON loitering_event (dwell_seconds DESC);

-- --------------------------------------------------------------------------
-- intrusion: JSONL sidecar is append-only and re-uploaded whole, so the
-- natural key (camera, instant) carries the idempotency.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS intrusion_event (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camera_key  VARCHAR(200) NOT NULL,
  occurred_at TIMESTAMPTZ  NOT NULL,
  asset_id    BIGINT       NULL REFERENCES media_asset(id) ON DELETE SET NULL,
  source_key  TEXT         NULL,
  CONSTRAINT uq_intrusion_event UNIQUE (camera_key, occurred_at)
);
CREATE INDEX IF NOT EXISTS idx_intrusion_occurred ON intrusion_event (occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_intrusion_camera   ON intrusion_event (camera_key);

-- --------------------------------------------------------------------------
-- walkins: the rich source. upper_hist/lower_hist are re-identification
-- vectors (512 floats each) and are deliberately NOT stored - they are never
-- useful in a UI and would bloat every row.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS walkin_detection (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camera_key    VARCHAR(200) NOT NULL,
  track_id      INTEGER      NOT NULL,
  raw_track_id  INTEGER      NULL,
  detected_at   TIMESTAMPTZ  NOT NULL,
  bbox          JSONB        NULL,
  confidence    NUMERIC(6,4) NULL,
  upper_garment VARCHAR(64)  NULL,
  lower_garment VARCHAR(64)  NULL,
  face_quality  JSONB        NULL,
  mode          VARCHAR(16)  NULL,
  crop_asset_id BIGINT       NULL REFERENCES media_asset(id) ON DELETE SET NULL,
  face_asset_id BIGINT       NULL REFERENCES media_asset(id) ON DELETE SET NULL,
  source_key    TEXT         NULL,
  CONSTRAINT uq_walkin_detection UNIQUE (camera_key, track_id, detected_at)
);
CREATE INDEX IF NOT EXISTS idx_walkin_detected ON walkin_detection (detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_walkin_camera   ON walkin_detection (camera_key);
CREATE INDEX IF NOT EXISTS idx_walkin_upper    ON walkin_detection (upper_garment);
CREATE INDEX IF NOT EXISTS idx_walkin_mode     ON walkin_detection (mode);

-- Colour chips, one row per extracted colour per region. Split out of the
-- detection so "everyone in a red upper today" is an indexed join, not a
-- jsonb scan.
CREATE TABLE IF NOT EXISTS walkin_colour (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  detection_id BIGINT      NOT NULL REFERENCES walkin_detection(id) ON DELETE CASCADE,
  region       VARCHAR(8)  NOT NULL,
  name         VARCHAR(48) NOT NULL,
  percentage   NUMERIC(5,1) NULL,
  rgb          INTEGER[]   NULL,
  CONSTRAINT ck_walkin_colour_region CHECK (region IN ('upper','lower'))
);
CREATE INDEX IF NOT EXISTS idx_wcolour_detection ON walkin_colour (detection_id);
CREATE INDEX IF NOT EXISTS idx_wcolour_lookup    ON walkin_colour (region, lower(name), percentage DESC);

-- --------------------------------------------------------------------------
-- Ingest bookkeeping. A watermark per prefix keeps each poll cheap; JSONL
-- files still get re-parsed when their ETag changes, because they are
-- rewritten in full.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inference_ingest_state (
  prefix        VARCHAR(120) PRIMARY KEY,
  last_key      TEXT         NULL,
  last_etag     VARCHAR(100) NULL,
  last_run_at   TIMESTAMPTZ  NULL,
  objects_seen  BIGINT       NOT NULL DEFAULT 0,
  rows_upserted BIGINT       NOT NULL DEFAULT 0,
  last_error    TEXT         NULL
);

-- Unified timeline across all four services, used by the /timeline endpoint.
CREATE OR REPLACE VIEW inference_timeline AS
  SELECT 'after_hours'::text AS service, s.id, s.camera_key, s.captured_at AS occurred_at,
         s.asset_id, NULL::integer AS dwell_seconds, s.global_id
    FROM after_hours_sighting s
  UNION ALL
  SELECT 'loitering', l.id, l.stream, l.started_at, l.asset_id, l.dwell_seconds, l.global_id
    FROM loitering_event l
  UNION ALL
  SELECT 'intrusion', i.id, i.camera_key, i.occurred_at, i.asset_id, NULL, NULL
    FROM intrusion_event i
  UNION ALL
  SELECT 'walkins', w.id, w.camera_key, w.detected_at, w.crop_asset_id, NULL, NULL
    FROM walkin_detection w;
