-- ---------------------------------------------------------------------------
-- Monitoring module: reinforcement feedback + administrator settings.
--
-- Apply: psql -U aiserver -d aiserver -f server/sql/monitoring_module.sql
-- Safe to re-run.
-- ---------------------------------------------------------------------------

-- --------------------------------------------------------------------------
-- Reinforcement learning feedback
--
-- A thumbs-down NEVER deletes anything. The detection row, its S3 media and
-- its timestamps all stay exactly as they are; only this side table records
-- the human judgement. Suppression from KPIs/analytics/tables is a READ-time
-- filter (see the notFalsePositive() helper in routes/inference.js), so a
-- mistaken thumbs-down is fully reversible and the sample survives for model
-- retraining.
--
-- detection_id is scoped by module, because ids are only unique per service
-- table (walkin_detection.id and loitering_event.id can collide).
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS reinforcement_feedback (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  detection_id  BIGINT       NOT NULL,
  module        VARCHAR(32)  NOT NULL,
  camera_id     VARCHAR(200) NULL,
  site_id       INTEGER      NULL,
  media_url     TEXT         NULL,      -- s3 key, not a presigned link (those expire)
  confidence    NUMERIC(6,4) NULL,
  feedback_type VARCHAR(24)  NOT NULL,  -- 'verified' | 'false_positive'
  feedback_by   VARCHAR(255) NULL,
  feedback_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  remarks       TEXT         NULL,
  status        VARCHAR(24)  NOT NULL DEFAULT 'open',
  CONSTRAINT ck_rf_module CHECK (module IN
    ('walkins','loitering','intrusion','after_hours','kitchen_unattended')),
  CONSTRAINT ck_rf_type CHECK (feedback_type IN ('verified','false_positive')),
  -- One standing verdict per detection; re-rating overwrites it.
  CONSTRAINT uq_rf_detection UNIQUE (module, detection_id)
);
CREATE INDEX IF NOT EXISTS idx_rf_module_type ON reinforcement_feedback (module, feedback_type);
CREATE INDEX IF NOT EXISTS idx_rf_at          ON reinforcement_feedback (feedback_at DESC);
CREATE INDEX IF NOT EXISTS idx_rf_camera      ON reinforcement_feedback (camera_id);

-- Suppression list used by every read path. Kept as a view so the filter is
-- defined in exactly one place.
CREATE OR REPLACE VIEW false_positive_detection AS
  SELECT module, detection_id
    FROM reinforcement_feedback
   WHERE feedback_type = 'false_positive';

-- --------------------------------------------------------------------------
-- Administrator settings
--
-- Key/value with a JSONB payload so a section can evolve without a migration.
-- `scope` is 'general' or one of the five modules. Settings that belong to the
-- on-prem detectors are additionally published to S3 as config.json - this
-- table is the source of truth, the S3 object is the delivery mechanism.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS app_setting (
  scope      VARCHAR(32)  NOT NULL,
  value      JSONB        NOT NULL DEFAULT '{}'::jsonb,
  version    INTEGER      NOT NULL DEFAULT 1,
  updated_by VARCHAR(255) NULL,
  updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
  PRIMARY KEY (scope)
);

-- Every settings change is auditable: who changed what, and to what.
CREATE TABLE IF NOT EXISTS app_setting_audit (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope      VARCHAR(32)  NOT NULL,
  old_value  JSONB        NULL,
  new_value  JSONB        NOT NULL,
  version    INTEGER      NOT NULL,
  changed_by VARCHAR(255) NULL,
  changed_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
  published  BOOLEAN      NOT NULL DEFAULT false,
  publish_error TEXT      NULL
);
CREATE INDEX IF NOT EXISTS idx_setting_audit_at ON app_setting_audit (changed_at DESC);

-- Defaults mirror what the on-prem services are documented to use today, so
-- the Settings screen opens showing the real current values rather than blanks.
INSERT INTO app_setting (scope, value) VALUES
  ('general', jsonb_build_object(
      'siteName', 'Biryani Katha',
      'timezone', 'Asia/Kolkata',
      'defaultReportDays', 7,
      'dateFormat', 'DD MMM YYYY',
      'timeFormat', 'HH:mm',
      'autoRefreshSeconds', 60,
      'notifyEmail', ''
   )),
  ('walkins', jsonb_build_object(
      'enabled', true, 'confidence', 0.5, 'minPersonSize', 40,
      'cooldownSeconds', 5, 'cameras', '[]'::jsonb
   )),
  ('loitering', jsonb_build_object(
      'enabled', true, 'thresholdSeconds', 180, 'confidence', 0.5, 'cameras', '[]'::jsonb
   )),
  ('intrusion', jsonb_build_object(
      'enabled', true, 'confidence', 0.5, 'alertDelaySeconds', 0,
      'zonesEnabled', true, 'roi', '[]'::jsonb, 'cameras', '[]'::jsonb
   )),
  ('after_hours', jsonb_build_object(
      'enabled', true, 'startHour', 21, 'endHour', 7, 'confidence', 0.5, 'cameras', '[]'::jsonb
   )),
  ('kitchen_unattended', jsonb_build_object(
      'enabled', true, 'maxUnattendedSeconds', 300, 'alertCooldownSeconds', 120,
      'confidence', 0.5, 'cameras', '[]'::jsonb
   ))
ON CONFLICT (scope) DO NOTHING;
