-- ---------------------------------------------------------------------------
-- Role-based access control.
--
-- Apply: psql -U aiserver -d aiserver -f server/sql/rbac.sql
-- Safe to re-run.
--
-- Model: a user has one role (anpr_app_users.role, which already exists), and a
-- role is granted a set of pages. Access is checked in two places and both
-- matter:
--   * the client hides nav entries and blocks routes, for usability
--   * the API refuses the underlying data, which is the part that is actually
--     load-bearing - hiding a menu item is not security
--
-- LOCKOUT GUARD: the 'admin' role is seeded with every page and the API refuses
-- to remove admin's access to the settings page. Without that, an administrator
-- can untick their own Settings checkbox and permanently lock everyone out of
-- the screen that grants access.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS app_role (
  role        VARCHAR(64) PRIMARY KEY,
  label       VARCHAR(120) NOT NULL,
  description TEXT NULL,
  -- A built-in role cannot be deleted; admin additionally cannot be locked out.
  is_builtin  BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One row per (role, page) that is ALLOWED. Absence means denied, so a new page
-- is closed by default rather than silently readable by everyone.
CREATE TABLE IF NOT EXISTS role_page_permission (
  role      VARCHAR(64)  NOT NULL REFERENCES app_role(role) ON DELETE CASCADE,
  page_key  VARCHAR(64)  NOT NULL,
  granted_by VARCHAR(255) NULL,
  granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (role, page_key)
);
CREATE INDEX IF NOT EXISTS idx_rpp_role ON role_page_permission (role);

-- Audit trail for access changes - who granted or revoked what.
CREATE TABLE IF NOT EXISTS rbac_audit (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role       VARCHAR(64)  NOT NULL,
  page_key   VARCHAR(64)  NULL,
  action     VARCHAR(24)  NOT NULL,   -- grant | revoke | role_created | role_deleted | user_role_changed
  target     VARCHAR(255) NULL,       -- affected user, for role assignment
  changed_by VARCHAR(255) NULL,
  changed_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_rbac_audit_at ON rbac_audit (changed_at DESC);

INSERT INTO app_role (role, label, description, is_builtin) VALUES
  ('admin',    'Administrator', 'Full access to every page, including access control.', true),
  ('manager',  'Manager',       'Operational monitoring and alerts, no configuration.', true),
  ('viewer',   'Viewer',        'Read-only view of the dashboard and monitoring pages.', true),
  ('operator', 'Camera Operator', 'Live camera views and active alerts only.', true)
ON CONFLICT (role) DO NOTHING;

-- Admin gets everything. The page list is kept in sync by the API at boot
-- (see ensureRbacSeed in routes/rbac.js), so a newly added page is granted to
-- admin automatically and to nobody else.
INSERT INTO role_page_permission (role, page_key)
SELECT 'admin', k FROM (VALUES
  ('dashboard'), ('daily_briefing'),
  ('monitoring_walkins'), ('monitoring_loitering'), ('monitoring_intrusion'),
  ('monitoring_after_hours'), ('monitoring_kitchen'),
  ('active_alerts'), ('cameras_online'), ('known_faces'),
  ('inference_viewer'), ('settings'), ('access_control')
) AS t(k)
ON CONFLICT DO NOTHING;

INSERT INTO role_page_permission (role, page_key)
SELECT 'manager', k FROM (VALUES
  ('dashboard'), ('daily_briefing'),
  ('monitoring_walkins'), ('monitoring_loitering'), ('monitoring_intrusion'),
  ('monitoring_after_hours'), ('monitoring_kitchen'),
  ('active_alerts'), ('cameras_online'), ('known_faces'), ('inference_viewer')
) AS t(k)
ON CONFLICT DO NOTHING;

INSERT INTO role_page_permission (role, page_key)
SELECT 'viewer', k FROM (VALUES
  ('dashboard'),
  ('monitoring_walkins'), ('monitoring_loitering'), ('monitoring_intrusion'),
  ('monitoring_after_hours'), ('monitoring_kitchen'), ('active_alerts')
) AS t(k)
ON CONFLICT DO NOTHING;

INSERT INTO role_page_permission (role, page_key)
SELECT 'operator', k FROM (VALUES ('cameras_online'), ('active_alerts'), ('dashboard')) AS t(k)
ON CONFLICT DO NOTHING;

-- Any existing user whose role is not in app_role would otherwise have no
-- permissions at all; register those roles so they are visible and editable.
INSERT INTO app_role (role, label, description)
SELECT DISTINCT u.role, initcap(u.role), 'Discovered from existing user accounts.'
  FROM anpr_app_users u
 WHERE u.role IS NOT NULL AND u.role <> ''
   AND NOT EXISTS (SELECT 1 FROM app_role r WHERE r.role = u.role)
ON CONFLICT (role) DO NOTHING;
